server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/movies
spring.datasource.username=postgres
spring.datasource.password=?ifren
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=fsweb